CREATE TABLE poscode(    
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT    
    ,POSTCODE INTEGER    
    ,ADDRESS  VARCHAR(255) NOT NULL   
    ,CITY VARCHAR(100) NOT NULL   
    ,STATE VARCHAR(100) NOT NULL);